
replicaCount: 1

image:
  repository: ai-ad-genesis-backend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4000

mongodb:
  uri: mongodb://mongodb-service:27017/ai_ad_system

secret:
  jwtSecret: "super-secret-123"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
