// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neqxfjcrbsfmnigszvxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcXhmamNyYnNmbW5pZ3N6dnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTk2MjcsImV4cCI6MjA2MDgzNTYyN30.oxAs0bEfZqZyxgHZYVsBhgwAxppRUbaDeR8xFbAplrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);